<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>


<div class="jumbotron">
    <h1 class="display-6">Movie Details - <?= $this->movieId; ?>(id:<?= $movie['id']; ?>)<br><?= $movie['headline'] ?></h1>

    <h1 class="display-6"><a href="/movie/list">See entire list</a></h1>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <?php if (0 < $this->movieId): ?>
                <li class="page-item"><a class="page-link" href="/movie/view/movie-id-<?= ($this->movieId - 1); ?>">Previous</a></li>
            <?php endif; ?>

            <?php if ($this->movieId < ($this->countedMovies - 1)): ?>
                <li class="page-item"><a class="page-link" href="/movie/view/movie-id-<?= ($this->movieId + 1); ?>">Next</a></li>
            <?php endif ?>
        </ul>
    </nav>
    <div class="row-cols-1 ">
        <div class="row-cols-2">
            <div class="col-1 float-left">
                Headline:
            </div>            
            <div class="col-10 ">
                <?php echo $movie['headline']; ?>&nbsp;(<?php echo $movie['year']; ?>)
                <?php for ($i = 1; $i <= 5; $i++): ?>
                    <span class="fa fa-star <?= ($i <= $movie['rating']) ? "checked" : ""; ?>"></span>             
                <?php endfor; ?>
            </div>
        </div>   

        <div class="row-cols-2">
            <div class="col-1 float-left">
                Class:
            </div>            
            <div class="col-10 ">
                <?php echo $movie['class']; ?>
            </div>
        </div>
        <div class="row-cols-2">
            <div class="col-1 float-left">
                Genres:
            </div>            
            <div class="col-10 ">
                <?php
                echo implode(', ', $movie['genres']);
                ?>
            </div>
        </div>
        <div class="row-cols-2">
            <div class="col-1 float-left">
                Duration:
            </div>            
            <div class="col-10 ">
                <?= $movie['duration'] / 60; ?>&nbsp;minutes
            </div>
        </div>        
        <div class="row-cols-2">
            <div class="col-1 float-left">
                Directors:
            </div>            
            <div class="col-10 ">
                <?php
                echo implode(', ', array_map(function($item) {
                            return $item['name'];
                        }, $movie['directors']));
                ?>
            </div>
        </div>
        <div class="row-cols-2">
            <div class="col-1 float-left">
                Cast:
            </div>            
            <div class="col-10 ">
                <?php
                echo implode(', ', array_map(function($item) {
                            return $item['name'];
                        }, $movie['cast']));
                ?>
            </div>
        </div>                
        <div class="media">
            <div class="media-body">
                <h5 class="mt-0 mb-1">Synopsis</h5>
                <?= nl2br($movie['synopsis']); ?>
                <a href="#" id="movie-details"> ... more</a>
                <div class="media-body" id="movie-details">
                    <hr>
                    <?= nl2br($movie['body']); ?>
                </div>
            </div>

            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <?php foreach ($movie['keyArtImages'] as $key => $image): ?>
                        <div class="carousel-item <?= ($key == 00) ? "active" : "" ?>">
                            <img src="/img/cache/<?= $image['cachedImage'] ?>" width="150px" class="d-block" alt="...">
                        </div>
                    <?php endforeach; ?>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

        </div>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <?php if (0 < $this->movieId): ?>
                    <li class="page-item"><a class="page-link" href="/movie/view/movie-id-<?= ($this->movieId - 1); ?>">Previous</a></li>
                <?php endif; ?>

                <?php if ($this->movieId < ($this->countedMovies - 1)): ?>
                    <li class="page-item"><a class="page-link" href="/movie/view/movie-id-<?= ($this->movieId + 1); ?>">Next</a></li>
                <?php endif ?>
            </ul>
        </nav>
        <?php if (isset($movie['reviewAuthor']) && isset($movie['quote'])): ?>
            <hr class="my-4">
            Comments:

            <div class="row-cols-2">
                <div class="col-2 float-left">
                    <?= $movie['reviewAuthor']; ?>
                </div>                        
                <div class="col-10 float-left">
                    <?= $movie['quote']; ?>
                </div>
            </div>
        <?php endif; ?>

    </div>
    <div class="clearfix"></div>

    <a class="btn btn-primary btn-sm" href="https://github.com/laminas" target="_blank">Check Laminas on GitHub &raquo;</a>
    <script>
        $(document).ready(function () {
            //$("div#movie-details").hide();
        });

        $("a#movie-details").on("click", function () {

            if ($("a#movie-details").text() == "... more") {
                $("a#movie-details").text('... less');
                $("div#movie-details").show();
            } else {
                $("a#movie-details").text('... more');
                $("div#movie-details").hide();
            }
        });
    </script> 
</div>


